language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
# command to run tests
script:
  - pip install -v -e .
  - mkdir ~/tmp
  - cp taup_distance/data/model_example* ~/tmp/
  - cp taup_distance/test_distance.py ~/tmp/
  - cd ~/tmp
  - python -m taup_distance.taup_distance ./model_example.nd 200 300
  - python -m taup_distance.taup_distance ./model_example_no_ic.nd 200 300
  - python -m taup_distance.taup_distance ./model_example.deck 200 300
  - coverage run ./test_distance.py
after_success:
  - codecov # submit coverage
